
/**
 * Guaranteed valid Base64 for Tanzil AI Avatar.
 * Using a clean, professional placeholder that is fully compatible with browsers.
 */
export const TANZIL_AVATAR_BASE64 = "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAwIiBoZWlnaHQ9IjQwMCIgdmlld0JveD0iMCAwIDQwMCA0MDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxyZWN0IHdpZHRoPSI0MDAiIGhlaWdodD0iNDAwIiByeD0iODAiIGZpbGw9IiMxNzE3MTciLz4KPGNpcmNsZSBjeD0iMjAwIiBjeT0iMTYwIiByPSI2MCIgZmlsbD0iI0Y5NzMxNiIvPgo8cGF0aCBkPSJNMTAwIDM0MEMxMDAgMjg0Ljc3MiAxNDQuNzczIDI0MCAyMDAgMjQwQzI1NS4yMjcgMjQwIDMwMCAyODQuNzcyIDMwMCAzNDBIMTAwWiIgZmlsbD0iI0Y5NzMxNiIvPgo8dGV4dCB4PSI1MCUiIHk9IjgwJSIgZmlsbD0id2hpdGUiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSI0MCIgZm9udC13ZWlnaHQ9ImJvbGQiIHRleHQtYW5jaG9yPSJtaWRkbGUiPlRBTlpJTCBBSTwvdGV4dD4KPC9zdmc+";
